version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: 'izota'
      POSTGRES_PASSWORD: '123qwe'
      POSTGRES_DB: 'izota-test'
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: 'rabbitmq:3-management'
    environment:
      RABBITMQ_DEFAULT_USER: 'izota'
      RABBITMQ_DEFAULT_PASS: '123qwe'
    ports:
      - "5672:5672"    # AMQP protocol
      - "15672:15672"  # Web management interface

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'izota'
      MONGO_INITDB_ROOT_PASSWORD: '123qwe'
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  redis:
    image: redis:latest
    environment:
      REDIS_PASSWORD: '123qwe'
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "redispassword"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data