name: 'Release'

on:
  push:
    branches: [ 'release' ]
  pull_request:
    types: [ opened, edited, reopened, synchronize, review_requested ]
    branches: [ 'release' ]
  workflow_call:

env:
  TAG_PREFIX: 'v'
  URL_REPO_BUILD: 'https://api.github.com/repos/baotran1989/build_and_deploy/dispatches'

jobs:
  BuildAndUnitTests:
    runs-on: ubuntu-latest # Lưu ý: lúc build có thể dùng public runner cho nhanh
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up DotNet SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration Release
      - name: Test
        run: dotnet test --no-build --configuration Release
  ReleaseDryRun:
    needs: [ BuildAndUnitTests ]
    if: |
      github.event_name == 'push'
    runs-on: ubuntu-latest # Lưu ý: lúc build có thể dùng public runner cho nhanh
    outputs:
      RESULT: ${{ steps.release_dry_run.outputs.result }}
      VERSION: ${{ steps.release_dry_run.outputs.releaseVersion }}
      RELEASE_NOTES: ${{ steps.release_dry_run.outputs.releaseNotes }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Release (dry-run)
        id: release_dry_run
        uses: btnguyen2k/action-semrelease@v3
        with:
          dry-run: true
          auto-mode: true
          github-token: ${{ secrets.GH_TOKEN }}
          tag-major-release: false
          tag-minor-release: false
          branches: ${{ github.ref_name }}
          tag-prefix: ${{ env.TAG_PREFIX }}
          tag-only: true
  BuildAndPushDockerImage:
    needs: [ ReleaseDryRun ]
    if: |
      github.ref == 'refs/heads/development' || github.ref == 'refs/heads/dev-cicd'
      || ${{ needs.ReleaseDryRun.outputs.VERSION }} == 'SUCCESS'
    runs-on: ubuntu-latest # Lưu ý: lúc build có thể dùng public runner cho nhanh
    outputs:
      DOCKER_IMAGE_TAG: ${{ steps.set_docker_image.outputs.DOCKER_IMAGE_TAG }}
    steps:
      - name: Dummy
        run: |
          echo "VERSION=${{ needs.ReleaseDryRun.outputs.VERSION }}"
          echo "RELEASE_NOTES=${{ needs.ReleaseDryRun.outputs.RELEASE_NOTES }}"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/izota-dummy:${{ needs.ReleaseDryRun.outputs.VERSION }}-sanbox-${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/izota-dummy:${{ needs.ReleaseDryRun.outputs.VERSION }}-sanbox
          file: ./Dockerfile
          context: ./
      - name: Set output docker image
        id: set_docker_image
        run: |
          echo "DOCKER_IMAGE_TAG=${{ needs.ReleaseDryRun.outputs.VERSION }}-sanbox" >> "$GITHUB_OUTPUT"


  DeployToSanbox:
    needs: [ ReleaseDryRun, BuildAndPushDockerImage ]
    if: |
      (github.ref == 'refs/heads/release')
      && ${{ needs.ReleaseDryRun.outputs.VERSION }} == 'SUCCESS'
    runs-on: ubuntu-latest
    environment: sanbox
    steps:
      - name: Dummy
        run: |
          echo "VERSION=${{ needs.ReleaseDryRun.outputs.VERSION }}"
          echo "RELEASE_NOTES=${{ needs.ReleaseDryRun.outputs.RELEASE_NOTES }}"
          echo "DOCKER_IMAGE_TAG=${{ needs.BuildAndPushDockerImage.outputs.DOCKER_IMAGE_TAG }}"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          name: ${{ needs.ReleaseDryRun.outputs.VERSION }}-sanbox
          tag: ${{ needs.ReleaseDryRun.outputs.VERSION }}-sanbox
          body: ${{ needs.ReleaseDryRun.outputs.RELEASE_NOTES }}
      - name: Trigger Deploy Sanbox
        run: |
          curl -X POST ${{ env.URL_REPO_BUILD }} \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.GH_TOKEN }} \
          --data '{"event_type": "dummy_service_release", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'",
          "ref_name": "'"${GITHUB_REF_NAME}"'",
          "environment": "sanbox",
          "docker_image_tag": "'"{{ needs.BuildAndPushDockerImage.outputs.DOCKER_IMAGE_TAG }}"'",
          "sha": "'"${GITHUB_SHA}"'"}}'

  DeployToProduction:
    needs: [ ReleaseDryRun, BuildAndPushDockerImage, DeployToSanbox ]
    if: |
      (github.ref == 'refs/heads/release')
      && ${{ needs.ReleaseDryRun.outputs.VERSION }} == 'SUCCESS'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Dummy
        run: |
          echo "VERSION=${{ needs.ReleaseDryRun.outputs.VERSION }}"
          echo "RELEASE_NOTES=${{ needs.ReleaseDryRun.outputs.RELEASE_NOTES }}"
          echo "DOCKER_IMAGE_TAG=${{ needs.BuildAndPushDockerImage.outputs.DOCKER_IMAGE_TAG }}"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          name: ${{ needs.ReleaseDryRun.outputs.VERSION }}
          tag: ${{ needs.ReleaseDryRun.outputs.VERSION }}
          body: ${{ needs.ReleaseDryRun.outputs.RELEASE_NOTES }}
      - name: Trigger Deploy Production
        run: |
          curl -X POST ${{ env.URL_REPO_BUILD }} \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.GH_TOKEN }} \
          --data '{"event_type": "dummy_service_release", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'",
          "ref_name": "'"${GITHUB_REF_NAME}"'",
          "environment": "production",
          "docker_image_tag": "'"{{ needs.BuildAndPushDockerImage.outputs.DOCKER_IMAGE_TAG }}"'",
          "sha": "'"${GITHUB_SHA}"'"}}'